---
# Some of the tasks include plugins installation.
# These are put into dotfile directories and referenced
# in dotfiles themselves, so I feel they kind of belong in
# this role.
- name: Clone dotfiles from Github
  ansible.builtin.git:
    repo: "{{ dotfiles_repository }}"
    dest: "{{ dotfiles_local_path }}"

- name: Prepare dotfile directories
  ansible.builtin.file:
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0755"
    path: "{{ item }}"
  loop:
    - "~/.vim"
    - "~/.vim/autoload"
    - "~/.config/tmux"
    - "~/.config/tmux/plugins"

- name: Install plugin managers
  block:
    - name: Install tmux plugin manager
      ansible.builtin.git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "~/.config/tmux/plugins/tpm"
        version: master
    - name: Install vim plugin manager
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "~/.vim/autoload/plug.vim"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: "0700"

# Using links instead of copying on purpose.
# Whenever I modify something in dotfiles I wouldn't need to copy
# done changes to repository and can commit and push straight away.
- name: Link dotfiles
  ansible.builtin.file:
    state: link
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "{{ dotfiles_local_path }}/vimrc", dest: "~/.vim/vimrc" }
    - { src: "{{ dotfiles_local_path }}/tmux.conf", dest: "~/.config/tmux/tmux.conf" }
  notify:
    - Reload plugins
