---
name: CI
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Run linter
        run: |
          yamllint -c .yamllint .
'on':
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:
